//> using scala "2.13"
//> using lib "org.typelevel::cats-effect:3.3.0"
//> using lib "com.lihaoyi::os-lib:0.7.8"
//> using lib "com.lihaoyi::upickle:1.4.2"
//> using lib "commons-codec:commons-codec:1.15"
//> using jar "../lib/adventofcode.jar"
//> using resourceDir "../resources"
